name = "AUCell"
uuid = "8db3d324-1814-4568-a261-40c86c609699"
authors = ["yan jing <yanjer123@qq.com>"]
version = "0.1.0"

[deps]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"

[compat]
HypothesisTests = "0.11.0"
julia = "1.7"